# Generated by Django 2.2.6 on 2019-10-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.IntegerField(choices=[(1, 'Бишкек'), (2, 'Чуйская область'), (3, 'Ошская область'), (4, 'Нарынская область'), (5, 'Жалал-Абадская область'), (6, 'Баткенская область'), (7, 'Иссык-Кульская область'), (8, 'Таласская область')], default=1)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ManyToManyField(related_name='patients', to='core.Hospital', verbose_name='Ваши поликлиники')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ManyToManyField(related_name='doctors', to='core.Hospital', verbose_name='Места работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
