# Generated by Django 2.2.6 on 2019-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='core.Hospital', verbose_name='Места работы'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, related_name='patients', to='core.Hospital', verbose_name='Ваши поликлиники'),
        ),
    ]
