# Generated by Django 2.2.2 on 2019-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191023_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form63',
            options={'verbose_name': 'Форму 63', 'verbose_name_plural': 'Форма 63 - Карта профилактических прививок'},
        ),
        migrations.AlterField(
            model_name='form63',
            name='result',
            field=models.IntegerField(choices=[('1', 'Положительный'), ('2', 'Отрицательный')], default=2),
        ),
    ]
