# Generated by Django 2.2.2 on 2019-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form63',
            name='result',
            field=models.IntegerField(choices=[(1, 'Положительный'), (2, 'Отрицательный')], default=2),
        ),
    ]
